### ISSUE TITLE
purposefully ignoring caught error?

### ISSUE THREAD

**Issue by tjwebb** [mapbox/tilelive#174]
https://github.com/mapbox/tilelive/blob/master/lib/tilelive.js#L121

This just wasted a half day of debugging because an error was bring thrown, but eaten by this `catch` handler. Probably other people will run into this as well. What's the point of a try/catch if you're just going to ignore the error?

**Comment by rclark** [comment]
This is intentional: the `tilelive.auto` function looks at a provided URI, and based on its protocol looks for modules to require _that might_ be what you're looking for. It is intended to silently try to figure out what you meant, and then allow [later code to return an error](https://github.com/mapbox/tilelive/blob/master/lib/tilelive.js#L95) telling you that the requested protocol has not been registered.

**Comment by tjwebb** [comment]
We should at least add a debugging statement in the `catch` block. Think about this from the perspective of someone who's new to tilelive and their code is silently *not working*. It's baffling. When the only way to debug is to read the entire codebase, you have a design flaw.
